version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      # POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    # command: ["postgres", "-c", "listen_addresses=*"]

  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 4000 --reload
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PHI_API_KEY=${PHI_API_KEY}
    depends_on:
      - db

  unicorn-ui:
    build:
      # context: ./unicorn-ui
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    # environment:
      # - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5151:80"
    volumes:
      - ./.pgadmin:/var/lib/pgadmin/data
    depends_on:
      - db
